/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import java.awt.event.MouseEvent;
import java.util.*;
import javax.swing.ImageIcon;
import negocio.Manejo;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
/**
 *
 * @author ESGEN
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    Manejo manejo;
    private int tx, ty;
    Map<String,String> paises = new HashMap();
    
    public App() {
        paises.put("CO", "COLOMBIA");
        paises.put("US", "ESTADOS UNIDOS");
        paises.put("BR", "BRASIL");
        paises.put("VE", "VENEZUELA");
        paises.put("CL", "CHILE");
        paises.put("MX", "MEXICO");
        paises.put("IT", "ITALIA");
        paises.put("ES", "ESPAÑA");
//        paises.put("", "");
        
        
        
        this.manejo = new Manejo();
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLabel_totalCasos.setText(manejo.infoMundo("total_cases"));
        jLabel_casos_hoy_dato.setText(manejo.infoMundo("total_new_cases_today"));
        jLabel_recuperados_dato.setText(manejo.infoMundo("total_recovered"));
        jLabel_muertes_hoy_dato.setText(manejo.infoMundo("total_new_deaths_today"));
        jLabel_muertes_dato.setText(manejo.infoMundo("total_deaths"));
        
        this.jLabel_fecha.setText(fechaFormato(manejo.getFecha()));
        jLabel_titulo_informe.setText("Informe GLOBAL");
        generarGrafico("MUNDO", "total_cases");
        
        setIconImage(new ImageIcon(getClass().getResource("/images/favicon_48x48.png")).getImage());
        
        // iconos banderas
//        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel_icono_brasil, "/images/countrys-flags/svg/colombia.svg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_icono_mundo = new javax.swing.JLabel();
        jLabel_icono_chile = new javax.swing.JLabel();
        jLabel_icono_colombia = new javax.swing.JLabel();
        jLabel_icono_usa = new javax.swing.JLabel();
        jLabel_icono_venezuela = new javax.swing.JLabel();
        jLabel_icono_brasil = new javax.swing.JLabel();
        jLabel_icono_mexico = new javax.swing.JLabel();
        jLabel_icono_espana = new javax.swing.JLabel();
        jLabel_icono_italia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_titulo_informe = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_totalCasos = new javax.swing.JLabel();
        jPanel_grafico = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel_casos_hoy = new javax.swing.JLabel();
        jLabel_recuperados = new javax.swing.JLabel();
        jLabel_muertes_hoy = new javax.swing.JLabel();
        jLabel_muertes = new javax.swing.JLabel();
        jLabel_casos_hoy_dato = new javax.swing.JLabel();
        jLabel_muertes_dato = new javax.swing.JLabel();
        jLabel_recuperados_dato = new javax.swing.JLabel();
        jLabel_muertes_hoy_dato = new javax.swing.JLabel();
        titlebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(90, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_icono_mundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icono_mundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_mundo_50x50.png"))); // NOI18N
        jLabel_icono_mundo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icono_mundo.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_mundo.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_mundo.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel_icono_mundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_icono_mundoMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_icono_mundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 60, 60));

        jLabel_icono_chile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icono_chile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos_banderas/chile.png"))); // NOI18N
        jLabel_icono_chile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icono_chile.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_chile.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_chile.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel_icono_chile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_icono_chileMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_icono_chile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 60, 60));

        jLabel_icono_colombia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icono_colombia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos_banderas/colombia.png"))); // NOI18N
        jLabel_icono_colombia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icono_colombia.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_colombia.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_colombia.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel_icono_colombia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_icono_colombiaMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_icono_colombia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 60, 60));

        jLabel_icono_usa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icono_usa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos_banderas/united-states-of-america.png"))); // NOI18N
        jLabel_icono_usa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icono_usa.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_usa.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_usa.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel_icono_usa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_icono_usaMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_icono_usa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 60, 60));

        jLabel_icono_venezuela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icono_venezuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos_banderas/venezuela.png"))); // NOI18N
        jLabel_icono_venezuela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icono_venezuela.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_venezuela.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_venezuela.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel_icono_venezuela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_icono_venezuelaMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_icono_venezuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 60, 60));

        jLabel_icono_brasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icono_brasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos_banderas/brazil.png"))); // NOI18N
        jLabel_icono_brasil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icono_brasil.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_brasil.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_brasil.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel_icono_brasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_icono_brasilMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_icono_brasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 60, 60));

        jLabel_icono_mexico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icono_mexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos_banderas/mexico.png"))); // NOI18N
        jLabel_icono_mexico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icono_mexico.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_mexico.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_mexico.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel_icono_mexico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_icono_mexicoMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_icono_mexico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 60, 60));

        jLabel_icono_espana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icono_espana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos_banderas/spain.png"))); // NOI18N
        jLabel_icono_espana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icono_espana.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_espana.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_espana.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel_icono_espana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_icono_espanaMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_icono_espana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 60, 60));

        jLabel_icono_italia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icono_italia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos_banderas/italy.png"))); // NOI18N
        jLabel_icono_italia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icono_italia.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_italia.setMinimumSize(new java.awt.Dimension(60, 60));
        jLabel_icono_italia.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel_icono_italia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_icono_italiaMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_icono_italia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 60, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 600));

        jPanel2.setBackground(new java.awt.Color(248, 253, 253));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Corbel Light", 0, 48)); // NOI18N
        jLabel4.setText("Coronavirus (CoVid-19)");

        jLabel_titulo_informe.setFont(new java.awt.Font("Lucida Console", 0, 22)); // NOI18N
        jLabel_titulo_informe.setForeground(new java.awt.Color(0, 25, 158));
        jLabel_titulo_informe.setText("Informe global");

        jLabel_fecha.setFont(new java.awt.Font("Txt", 1, 24)); // NOI18N
        jLabel_fecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_fecha.setText("00/00/00");

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ultimo informe");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel_titulo_informe, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_fecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jLabel_titulo_informe)
                .addGap(84, 84, 84))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 140));

        jPanel6.setBackground(new java.awt.Color(0, 131, 249));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Total de casos:");

        jLabel_totalCasos.setFont(new java.awt.Font("Swis721 Lt BT", 0, 48)); // NOI18N
        jLabel_totalCasos.setForeground(new java.awt.Color(0, 0, 102));
        jLabel_totalCasos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_totalCasos.setText("------------");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_totalCasos, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel_totalCasos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel_grafico.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_graficoLayout = new javax.swing.GroupLayout(jPanel_grafico);
        jPanel_grafico.setLayout(jPanel_graficoLayout);
        jPanel_graficoLayout.setHorizontalGroup(
            jPanel_graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel_graficoLayout.setVerticalGroup(
            jPanel_graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel_casos_hoy.setFont(new java.awt.Font("Open Sans Semibold", 1, 14)); // NOI18N
        jLabel_casos_hoy.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_casos_hoy.setText("Casos hoy");
        jLabel_casos_hoy.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel_casos_hoy.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel_casos_hoy.setName(""); // NOI18N
        jLabel_casos_hoy.setPreferredSize(new java.awt.Dimension(114, 34));

        jLabel_recuperados.setFont(new java.awt.Font("Open Sans Semibold", 1, 14)); // NOI18N
        jLabel_recuperados.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_recuperados.setText("Recuperados");
        jLabel_recuperados.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel_recuperados.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel_recuperados.setName(""); // NOI18N
        jLabel_recuperados.setPreferredSize(new java.awt.Dimension(114, 34));

        jLabel_muertes_hoy.setFont(new java.awt.Font("Open Sans Semibold", 1, 14)); // NOI18N
        jLabel_muertes_hoy.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_muertes_hoy.setText("Muertes hoy");
        jLabel_muertes_hoy.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel_muertes_hoy.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel_muertes_hoy.setName(""); // NOI18N
        jLabel_muertes_hoy.setPreferredSize(new java.awt.Dimension(114, 34));

        jLabel_muertes.setFont(new java.awt.Font("Open Sans Semibold", 1, 14)); // NOI18N
        jLabel_muertes.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_muertes.setText("Total muertes");
        jLabel_muertes.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel_muertes.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel_muertes.setName(""); // NOI18N
        jLabel_muertes.setPreferredSize(new java.awt.Dimension(114, 34));

        jLabel_casos_hoy_dato.setFont(new java.awt.Font("Swis721 Lt BT", 0, 30)); // NOI18N
        jLabel_casos_hoy_dato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_casos_hoy_dato.setText("0000000000");
        jLabel_casos_hoy_dato.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel_casos_hoy_dato.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel_casos_hoy_dato.setName(""); // NOI18N
        jLabel_casos_hoy_dato.setPreferredSize(new java.awt.Dimension(114, 34));

        jLabel_muertes_dato.setFont(new java.awt.Font("Swis721 Lt BT", 0, 30)); // NOI18N
        jLabel_muertes_dato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_muertes_dato.setText("0000000000");
        jLabel_muertes_dato.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel_muertes_dato.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel_muertes_dato.setName(""); // NOI18N
        jLabel_muertes_dato.setPreferredSize(new java.awt.Dimension(114, 34));

        jLabel_recuperados_dato.setFont(new java.awt.Font("Swis721 Lt BT", 0, 30)); // NOI18N
        jLabel_recuperados_dato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_recuperados_dato.setText("0000000000");
        jLabel_recuperados_dato.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel_recuperados_dato.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel_recuperados_dato.setName(""); // NOI18N
        jLabel_recuperados_dato.setPreferredSize(new java.awt.Dimension(114, 34));

        jLabel_muertes_hoy_dato.setFont(new java.awt.Font("Swis721 Lt BT", 0, 30)); // NOI18N
        jLabel_muertes_hoy_dato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_muertes_hoy_dato.setText("0000000000");
        jLabel_muertes_hoy_dato.setMaximumSize(new java.awt.Dimension(34, 34));
        jLabel_muertes_hoy_dato.setMinimumSize(new java.awt.Dimension(34, 34));
        jLabel_muertes_hoy_dato.setName(""); // NOI18N
        jLabel_muertes_hoy_dato.setPreferredSize(new java.awt.Dimension(114, 34));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_muertes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_casos_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_recuperados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_muertes_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_muertes_hoy_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_muertes_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_casos_hoy_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_recuperados_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_casos_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_casos_hoy_dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_recuperados_dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_recuperados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_muertes_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_muertes_hoy_dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_muertes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_muertes_dato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel_grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 900, 420));

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 900, 560));

        titlebar.setBackground(new java.awt.Color(255, 255, 255));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 51, 51));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel3.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titlebarLayout = new javax.swing.GroupLayout(titlebar);
        titlebar.setLayout(titlebarLayout);
        titlebarLayout.setHorizontalGroup(
            titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlebarLayout.createSequentialGroup()
                .addGap(0, 848, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titlebarLayout.setVerticalGroup(
            titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlebarLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        getContentPane().add(titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 900, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen() - tx - 60, evt.getYOnScreen() - ty);
    }//GEN-LAST:event_titlebarMouseDragged

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        // TODO add your handling code here:
        tx = evt.getX();
        ty = evt.getY();
    }//GEN-LAST:event_titlebarMousePressed
    
    private String fechaFormato(String fecha){        
        char[] charFecha = manejo.getFecha().toCharArray();
        String dia, mes="", ano;
        int pos=0;
        //formato de fechas:
        //  "4/20/20"
        //  -01234567-
        //  "11/09/20"
        if("/".equals(""+charFecha[2])){            
            pos++;
            mes=charFecha[1]+"";
        }
        dia=""+charFecha[2+pos]+charFecha[3+pos];
        ano="20"+charFecha[5+pos]+charFecha[6+pos];
        mes+=""+charFecha[0]+mes;
        return dia+"/"+mes+"/"+ano;
    }
    
    private void presentarPais(String pais){        
        //jLabel_.setText(manejo.infoPais("CO", "total_"));
        jLabel_totalCasos.setText(manejo.infoPais(pais, "total_cases"));
        jLabel_casos_hoy_dato.setText(manejo.infoPais(pais, "new_daily_cases"));
        jLabel_recuperados_dato.setText(manejo.infoPais(pais, "total_recoveries"));
        jLabel_muertes_hoy_dato.setText(manejo.infoPais(pais, "new_daily_deaths"));
        jLabel_muertes_dato.setText(manejo.infoPais(pais, "total_deaths"));
        jLabel_titulo_informe.setText("Informe "+this.paises.get(pais));
        
        generarGrafico(pais, "total_cases");
    }
    
    private void jLabel_icono_chileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_icono_chileMouseClicked
        // TODO add your handling code here:
        presentarPais("CL");
        
        
    }//GEN-LAST:event_jLabel_icono_chileMouseClicked

    private void jLabel_icono_mundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_icono_mundoMouseClicked
        // TODO add your handling code here:
        this.jLabel_totalCasos.setText(manejo.infoMundo("total_cases"));
        jLabel_casos_hoy_dato.setText(manejo.infoMundo("total_new_cases_today"));
        jLabel_recuperados_dato.setText(manejo.infoMundo("total_recovered"));
        jLabel_muertes_hoy_dato.setText(manejo.infoMundo("total_new_deaths_today"));
        jLabel_muertes_dato.setText(manejo.infoMundo("total_deaths"));
        jLabel_titulo_informe.setText("Informe GLOBAL");
        
        generarGrafico("MUNDO", "total_cases");
        
    }//GEN-LAST:event_jLabel_icono_mundoMouseClicked

    private void jLabel_icono_colombiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_icono_colombiaMouseClicked
        // TODO add your handling code here:
        presentarPais("CO");
    }//GEN-LAST:event_jLabel_icono_colombiaMouseClicked

    private void jLabel_icono_usaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_icono_usaMouseClicked
        // TODO add your handling code here:
        presentarPais("US");
    }//GEN-LAST:event_jLabel_icono_usaMouseClicked

    private void jLabel_icono_venezuelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_icono_venezuelaMouseClicked
        // TODO add your handling code here:
        presentarPais("VE");
    }//GEN-LAST:event_jLabel_icono_venezuelaMouseClicked

    private void jLabel_icono_brasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_icono_brasilMouseClicked
        // TODO add your handling code here:
        presentarPais("BR");
    }//GEN-LAST:event_jLabel_icono_brasilMouseClicked

    private void jLabel_icono_mexicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_icono_mexicoMouseClicked
        // TODO add your handling code here:
        presentarPais("MX");
    }//GEN-LAST:event_jLabel_icono_mexicoMouseClicked

    private void jLabel_icono_espanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_icono_espanaMouseClicked
        // TODO add your handling code here:
        presentarPais("ES");
    }//GEN-LAST:event_jLabel_icono_espanaMouseClicked

    private void jLabel_icono_italiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_icono_italiaMouseClicked
        // TODO add your handling code here:
        presentarPais("IT");
    }//GEN-LAST:event_jLabel_icono_italiaMouseClicked
    
    private void generarGrafico(String pais, String info){
//        XYSeries oSeries = new XYSeries("curva contagios");
//        int i = 1;
//        
//        ArrayList<Long> array = manejo.obtenerHistorico(pais, info);
//        for(long dato : array){            
//            oSeries.add(i++, dato);
//        }
//        
//        XYSeriesCollection oDataset = new XYSeriesCollection();
//        oDataset.addSeries(oSeries);
//        
//        JFreeChart oChart = ChartFactory.createXYLineChart("Total casos", "dias", "cant", oDataset, PlotOrientation.VERTICAL, true, false, false);
//        ChartPanel oPanel = new ChartPanel(oChart);
//        jPanel_grafico.setLayout(new java.awt.BorderLayout());
//        jPanel_grafico.add(oPanel);
//        
//        jPanel_grafico.validate();
        
        ArrayList<Long> array;
        XYSeries oSeries;
        XYSeriesCollection oDataset = new XYSeriesCollection();
        int i = 1;
        String value;
        
        for(Map.Entry<String, String> entry : paises.entrySet()) {
            value = ("MUNDO".equals(pais))?entry.getKey():pais;
            array = manejo.obtenerHistorico(value, info);
            oSeries = ("MUNDO".equals(pais))?new XYSeries(entry.getValue()) : new XYSeries(paises.get(pais));
            for (long dato : array) {
                oSeries.add(i++, dato);
            }
            i=1;
            oDataset.addSeries(oSeries);
            if (!"MUNDO".equals(pais)) {
                break;
            }
        }       
        
        JFreeChart oChart = ChartFactory.createXYLineChart("Total casos", "días", "infectados", oDataset, PlotOrientation.VERTICAL, true, false, false);
        ChartPanel oPanel = new ChartPanel(oChart);
        jPanel_grafico.setLayout(new java.awt.BorderLayout());
        jPanel_grafico.add(oPanel);
        
        jPanel_grafico.validate();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_casos_hoy;
    private javax.swing.JLabel jLabel_casos_hoy_dato;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_icono_brasil;
    private javax.swing.JLabel jLabel_icono_chile;
    private javax.swing.JLabel jLabel_icono_colombia;
    private javax.swing.JLabel jLabel_icono_espana;
    private javax.swing.JLabel jLabel_icono_italia;
    private javax.swing.JLabel jLabel_icono_mexico;
    private javax.swing.JLabel jLabel_icono_mundo;
    private javax.swing.JLabel jLabel_icono_usa;
    private javax.swing.JLabel jLabel_icono_venezuela;
    private javax.swing.JLabel jLabel_muertes;
    private javax.swing.JLabel jLabel_muertes_dato;
    private javax.swing.JLabel jLabel_muertes_hoy;
    private javax.swing.JLabel jLabel_muertes_hoy_dato;
    private javax.swing.JLabel jLabel_recuperados;
    private javax.swing.JLabel jLabel_recuperados_dato;
    private javax.swing.JLabel jLabel_titulo_informe;
    private javax.swing.JLabel jLabel_totalCasos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_grafico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel titlebar;
    // End of variables declaration//GEN-END:variables
}
